SELECT * 
FROM [VENTAS 2023 CARPIO]

-- RENOMBRANDO COLUMNAS

EXEC sp_rename 'VENTAS 2023 CARPIO.FEC_MOVI', 'FECHA', 'COLUMN'
EXEC sp_rename 'VENTAS 2023 CARPIO.COD_DOCU', 'TIPO_DE_COMPROBANTE', 'COLUMN'
EXEC sp_rename 'VENTAS 2023 CARPIO.SER_DOCU', 'SERIE', 'COLUMN'
EXEC sp_rename 'VENTAS 2023 CARPIO.NUM_DOCU', 'CORRELATIVO', 'COLUMN'
EXEC sp_rename 'VENTAS 2023 CARPIO.TDO_CORR', 'TIPO_DOCUMENTO', 'COLUMN'
EXEC sp_rename 'VENTAS 2023 CARPIO.DES_CORR', 'NOMBRE', 'COLUMN'
EXEC sp_rename 'VENTAS 2023 CARPIO.IMP_TOTA', 'TOTAL', 'COLUMN'
EXEC sp_rename 'VENTAS 2023 CARPIO.EST_DOCU', 'ESTADO', 'COLUMN'
EXEC sp_rename 'VENTAS 2023 CARPIO.ANO_EJER', 'AÑO', 'COLUMN'
EXEC sp_rename 'VENTAS 2023 CARPIO.MES_EJER', 'MES', 'COLUMN'
EXEC sp_rename 'VENTAS 2023 CARPIO.DOC_CORR', 'DOCUMENTO', 'COLUMN'
--IDENTIFICANDO TIPO DE COMBROBANTE(BOLETA,FACTURA)
SELECT TIPO_DE_COMPROBANTE, COUNT (TIPO_DE_COMPROBANTE)
FROM  [VENTAS 2023 CARPIO]
GROUP BY TIPO_DE_COMPROBANTE


SELECT TIPO_DE_COMPROBANTE,
CASE WHEN TIPO_DE_COMPROBANTE = 3 THEN 'BOLETA'
     WHEN TIPO_DE_COMPROBANTE = 7 THEN 'NOTA DE CREDITO'
	 WHEN TIPO_DE_COMPROBANTE = 1 THEN 'FACTURA'
	 END AS TIPO_COMPROBANTE
FROM [VENTAS 2023 CARPIO]

--UPDATE [VENTAS 2023 CARPIO]
--SET TIPO_DE_COMPROBANTE = 
--CASE WHEN TIPO_DE_COMPROBANTE = 3 THEN 'BOLETA'
    -- WHEN TIPO_DE_COMPROBANTE = 7 THEN 'NOTA DE CREDITO'
	 --WHEN TIPO_DE_COMPROBANTE = 1 THEN 'FACTURA'
	 --END


ALTER TABLE [VENTAS 2023 CARPIO]
ADD TIPO_COMPROBANTE VARCHAR(250)

UPDATE [VENTAS 2023 CARPIO]
SET TIPO_COMPROBANTE = 
CASE WHEN TIPO_DE_COMPROBANTE = 3 THEN 'BOLETA'
     WHEN TIPO_DE_COMPROBANTE = 7 THEN 'NOTA DE CREDITO'
	 WHEN TIPO_DE_COMPROBANTE = 1 THEN 'FACTURA'
	 END

-- CAMBIANDO 1 A DNI Y 6 A RUC EN TIPO_DOCUMENTO
SELECT TIPO_DOCUMENTO, COUNT (TIPO_DOCUMENTO)
FROM  [VENTAS 2023 CARPIO]
GROUP BY TIPO_DOCUMENTO


SELECT * 
FROM[VENTAS 2023 CARPIO]
WHERE TIPO_DOCUMENTO = 4


--QUITANDO VALORES NULOS Y VACIOS (0) 
SELECT ESTADO,COUNT(ESTADO)
FROM [VENTAS 2023 CARPIO]
GROUP BY ESTADO


-- NOMBRANDO VALORES VALIDOS Y NULOS
SELECT ESTADO,
CASE WHEN ESTADO = 1 THEN 'VALIDO'
     WHEN ESTADO = 2 THEN 'ANULADO'
	  END AS VALIDEZ
FROM [VENTAS 2023 CARPIO]

ALTER TABLE [VENTAS 2023 CARPIO]
ADD VALIDEZ VARCHAR (255)



UPDATE [VENTAS 2023 CARPIO]
SET VALIDEZ = 
CASE WHEN ESTADO = '1' THEN 'VALIDO'
     WHEN ESTADO = '2' THEN 'ANULADO'
	 END 
--DESPEJANDO COLUMNAS SIN USO
ALTER TABLE [VENTAS 2023 CARPIO]
DROP COLUMN TIPO_DE_COMPROBANTE,ESTADO
--CAMBIANDO VALIDEZ POR ESTADO
EXEC sp_rename 'VENTAS 2023 CARPIO.VALIDEZ', 'ESTADO', 'COLUMN'













